# This is a basic workflow to help you get started with Actions

name: Matrix Workflow

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Setting a matrix strategy
  example_matrix:
    strategy:
      matrix:
       # Using OS as the first strategy
        os: [windows-latest, ubuntu-latest]
        node: [14, 16]
        include:
          - os: windows-latest
            node: 16
            npm: 6

    # Setting up the OS
    runs-on: ${{ matrix.os }}
  
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      # Setting npm version with a condition
      - if: ${{ matrix.npm }}
        run: npm instal -g npm@${{ matrix.npm }}
      
      # Checking the npm version
      - run: npm --version 
